### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#186]
- [x] https://acturtle.com/static/img/17/cash-flow-model-overview.webp
- [x] https://acturtle.com/static/img/39/output_individual_2.png
- [x] update acturtle.com
- [x] update life insurance + life annuity tutorial and docs according to changes in blog
